package com.example.ucmhomedemo21;

public class GlobalViewIds {
	
	public enum Ids {
		
		ADDRESS_BAR_BACKGROUND,
		ADDRESS_BAR_EDIT_TEXT,
		ADDRESS_BAR_EDIT_TEXT_SEARCH,
		ADDRESS_BAR_RIGHT_LINE,
		ADDRESS_BAR_LEFT_LINE,
		ADDRESS_BAR_STAR_BUTTON,
		
		QUICK_BUTTON_BACKGROUND,
		QUICK_BUTTON,
		
		BOTTOM_BAR_BUTTON_IMAGE,
		BOTTOM_BAR_BUTTON,
		BOTTOM_BAR_ITEM1, BOTTOM_BAR_ITEM2, BOTTOM_BAR_ITEM3, BOTTOM_BAR_ITEM4, BOTTOM_BAR_ITEM5,
		
		HOT_SITES_ITEM_DESCRIIPTION_TEXT_ID,
		HOT_SITES_ITEM_BACKGROUND,
		HOT_SITES_ITEM_ICON,
		
		NAVIGATION_ITEM_ICON,
		NAVIGATION_ITEM_TEXT,
		NAVIGATION_ITEM_DETAIL_TEXT,
		NAVIGATION_ITEM_BUTTON,
		NAVIGATION_ITEM_ACCESSORY_ICON,
		
		ADDRESS_BAR,
		TOP_BAR,
		BOTTOM_BAR,
		NAVIGATION_LIST_VIEW,
		HOT_SITES_LIST_VIEW,
		SCROLL_VIEW,
	}

	public static int getIdOf(Ids addressBarBackground) {
		return 10003 + addressBarBackground.ordinal();
	}

}
